services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    plan: free
    repo: https://github.com/ТВОЙ_ЮЗЕРНЕЙМ/ТВОЙ_РЕПОЗИТОРИЙ
    branch: main
    autoDeploy: true
